// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB39-5YAVM9QcM-dNM_gA2WPzv8jfU3pA',
    appId: '1:652935715305:android:a652110ecd846bf00fd378',
    messagingSenderId: '652935715305',
    projectId: 'flutterapplication1-c68b1',
    storageBucket: 'flutterapplication1-c68b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1j43ej_-52Ix8S7jkODRiZHiJEmGAzQI',
    appId: '1:652935715305:ios:bad6bae07fc061a90fd378',
    messagingSenderId: '652935715305',
    projectId: 'flutterapplication1-c68b1',
    storageBucket: 'flutterapplication1-c68b1.appspot.com',
    androidClientId: '652935715305-4gcgq9vt6b4ppu12473nibettbcl2mrn.apps.googleusercontent.com',
    iosClientId: '652935715305-9k1tknsoetvdblrlrqru74ll3lu59l0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.docsaver',
  );
}
